### ISSUE TITLE
screen just comes up blank

### ISSUE THREAD

**Issue by ConceptCodes** [vuetifyjs/theme-freelancer#1]
i cloned the repo, ran npm install and then npm run serve, and all that appears is a blank screen.

**Comment by jagould2012** [comment]
Had the same issue - looks like its the version of Vuetify. Try this:

```
npm i --save vuetify@^1.5.9
```

then

```
npm run serve
```

Works for me.

**Comment by ConceptCodes** [comment]
thank you so much , it worked
